export const clerkAppearance = {
  variables: {
    colorBackground: 'transparent',
    colorInputBackground: '#E6DCC9',
    colorText: '#1F1A15',
    colorTextSecondary: '#6B5F51',
    colorPrimary: '#3B6FB5',
    colorTextOnPrimaryBackground: '#ffffff',
    borderRadius: '6px',
    fontFamily: '"Geist", ui-sans-serif, system-ui, sans-serif',
    fontSize: '14px',
  },
  elements: {
    rootBox: { width: '100%' },
    cardBox: {
      boxShadow: 'none',
      border: 'none',
      background: 'transparent',
      width: '100%',
      overflow: 'visible',
    },
    card: {
      boxShadow: 'none',
      background: 'transparent',
      border: 'none',
      padding: '0',
      width: '100%',
      maxWidth: '100%',
      gap: '1.25rem',
      overflow: 'visible',
    },
    header: { display: 'none' },
    socialButtonsBlockButton: {
      border: '1px solid #D9CBB0',
      backgroundColor: '#EFE7DA',
      color: '#1F1A15',
    },
    dividerText: {
      color: '#8F8273',
      fontSize: '11px',
      letterSpacing: '0.08em',
    },
    dividerLine: { backgroundColor: '#D9CBB0' },
    formFieldLabel: {
      color: '#6B5F51',
      fontSize: '11px',
      letterSpacing: '0.06em',
      textTransform: 'uppercase',
      fontWeight: '500',
    },
    formFieldInput: {
      backgroundColor: '#EFE7DA',
      borderColor: '#D9CBB0',
      color: '#1F1A15',
    },
    formButtonPrimary: {
      backgroundColor: '#3B6FB5',
      color: '#ffffff',
    },
    footer: { background: 'transparent' },
    footerAction: { color: '#6B5F51' },
    footerActionLink: { color: '#3B6FB5' },
    identityPreviewText: { color: '#1F1A15' },
    identityPreviewEditButton: { color: '#3B6FB5' },
  },
};
