# This is a basic workflow to help you get started with Actions

name: Auto Assign Milestones

# Controls when the workflow will run
on:
  issues:
    types: [opened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "assign-milestone"
   assign-milestone:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const milestones = await github.rest.issues.listMilestonesForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });

            let milestoneTitle = null;

            if(issue.labels.some(label => label.name === 'feature')) {
              milestoneTitle = 'MVP - Core Features';
            } else if(issue.labels.some(label => label.name === 'ai-integration')) {
              milestoneTitle = 'AI Integration';
            } else if(issue.labels.some(label => label.name === 'deployment')) {
              milestoneTitle = 'Billing & Deployment';
            } else if(issue.labels.some(label => label.name === 'testing')) {
              milestoneTitle = 'Testing & Documentation';
            } else if(issue.labels.some(label => label.name === 'enhancement')) {
              milestoneTitle = 'Launch & Showcase';
            }

            if(milestoneTitle) {
              const milestone = milestones.data.find(m => m.title === milestoneTitle);
              if(milestone) {
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  milestone: milestone.number
                });
                console.log(`Assigned milestone: ${milestoneTitle}`);
              }
            }
